apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  NEXTAUTH_URL: {{ .Values.config.nextAuthUrl | quote }}
  NODE_ENV: "production"