apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.backend.name }}
        image: {{ .Values.workload.image }}
        imagePullPolicy: Always
        
        # Health checks disabled temporarily for debugging
        # livenessProbe:
        #   httpGet:
        #     path: /api/health # Adjust to your actual health check endpoint
        #     port: 3000
        #   initialDelaySeconds: 30
        #   periodSeconds: 20
        # readinessProbe:
        #   httpGet:
        #     path: /api/health # Adjust to your actual health check endpoint
        #     port: 3000
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        
        envFrom:
        - configMapRef:
            name: {{ include "backend.fullname" . }}-configmap
        - secretRef:
            name: {{ include "backend.fullname" . }}-secret
        
        # Add debug environment variables
        # For production, consider removing DEBUG and setting NODE_ENV via ConfigMap
        env:
        
        resources:
          requests:
            memory: {{ .Values.workload.resources.requests.memory }}
            cpu: {{ .Values.workload.resources.requests.cpu }}
          limits:
            memory: {{ .Values.workload.resources.limits.memory }}
            cpu: {{ .Values.workload.resources.limits.cpu }}
        ports:
        - containerPort: 3000
