apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Construct the database URL from database chart values
  DATABASE_URL: "postgresql://{{ .Values.database.auth.username }}:{{ .Values.database.auth.password }}@{{ .Values.database.fullnameOverride }}.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.database.auth.database }}?schema=public"
  NEXTAUTH_SECRET: {{ .Values.secret.nextAuthSecret | quote }}