apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- include "backend.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80 # Port của Service
      targetPort: 3000 # Port mà ứng dụng Next.js của bạn đang chạy bên trong container
  type: ClusterIP