# PostgreSQL Exporter Configuration
replicaCount: 1

image:
  repository: quay.io/prometheuscommunity/postgres-exporter
  tag: "v0.15.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# PostgreSQL connection settings
config:
  datasource:
    host: postgres.meo-stationery.svc.cluster.local
    port: "5432"
    database: "meo_stationery"
    userSecret:
      name: postgres-secret
      key: POSTGRES_USER
    passwordSecret:
      name: postgres-secret
      key: POSTGRES_PASSWORD

serviceMonitor:
  enabled: true
  labels:
    release: prometheus