- name: Prepare all nodes for Kubernetes
  hosts: all
  become: yes
  vars:
    ansible_become_timeout: 60
  tasks:
    - name: Clean up broken Helm apt repo (if exists)
      file:
        path: /etc/apt/sources.list.d/helm-stable-debian.list
        state: absent

    - name: Disable swap immediately
      command: swapoff -a
      when: ansible_swaptotal_mb | int > 0

    - name: Ensure swap is disabled permanently
      replace:
        path: /etc/fstab
        regexp: '(^.*swap.*$)'
        replace: '# \1'

    - name: Load kernel modules for Kubernetes
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Ensure kernel modules load on boot
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        mode: '0644'

    - name: Set sysctl params for Kubernetes networking
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        mode: '0644'

    - name: Apply sysctl params
      command: sysctl --system

    - name: Ensure keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download and install Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker APT repository
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
        https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
        > /etc/apt/sources.list.d/docker.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required system packages for Kubernetes
      apt:
        name:
          - conntrack
          - curl
          - iptables
          - ipset
          - socat
          - ipvsadm
        state: present
        update_cache: yes

    - name: Install containerd
      apt:
        name: containerd.io
        state: present
        update_cache: yes

    - name: Generate default containerd config
      shell: containerd config default | tee /etc/containerd/config.toml


    - name: Enable SystemdCgroup in containerd config
      replace:
        path: /etc/containerd/config.toml
        regexp: '^(\s*)SystemdCgroup = false'
        replace: '\1SystemdCgroup = true'
      notify:
      - Restart containerd


    - name: Delete existing keys
      file:
        path: /usr/share/keyrings/kubernetes-archive-keyring.asc
        state: absent
        # mode: '0755'

    - name: Download Kubernetes Release key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
        dest: /tmp/k8s-release.key
        mode: '0644'
        force: yes

    - name: Dearmor Kubernetes key
      shell: cat /tmp/k8s-release.key | gpg --dearmor --yes -o /usr/share/keyrings/kubernetes-archive-keyring.gpg
      # args:
      #   creates: /usr/share/keyrings/kubernetes-archive-keyring.gpg

    - name: Add Kubernetes APT repository
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
      register: k8s_repo



    - name: Update apt cache if Kubernetes repo or key changed
      apt:
        update_cache: yes
      when: k8s_repo.changed




    - name: Download Helm binary
      unarchive:
        src: https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz
        dest: /tmp
        remote_src: yes
    
    - name: Move Helm binary to path
      copy:
        src: /tmp/linux-amd64/helm
        dest: /usr/local/bin/helm
        mode: '0755'
        remote_src: yes

    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold Kubernetes packages at current version
      shell: apt-mark hold kubelet kubeadm kubectl

    - name: Clean up disk space (Docker images and unused resources)
      shell: |
        # Clean up unused Docker images (older than 12 hours)
        docker system prune -af --filter "until=12h" || true
        # Clean up old logs
        journalctl --vacuum-time=2d || true
        # Show disk usage
        df -h / | tail -1
      ignore_errors: yes
      when: ansible_connection != 'local'

  handlers:
    - name: Restart containerd
      service:
        name: containerd
        state: restarted
        enabled: true
      ignore_errors: yes
      poll: 10
      ignore_errors: yes