- name: Check All Logs and Debug Connection Issue
  hosts: masters
  become: yes
  vars:
    master_kubeconfig: /home/ubuntu/.kube/config

  tasks:
    - name: Check ingress controller pods
      shell: kubectl get pods -n ingress-nginx -l app.kubernetes.io/component=controller
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: ingress_pods

    - name: Show ingress pods
      debug:
        var: ingress_pods.stdout_lines

    - name: Check ingress controller logs (last 50 lines)
      shell: kubectl logs -n ingress-nginx -l app.kubernetes.io/component=controller --tail=50
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: ingress_logs
      ignore_errors: yes

    - name: Show ingress controller logs
      debug:
        var: ingress_logs.stdout_lines

    - name: Check backend pods
      shell: kubectl get pods -n meo-stationery -l app.kubernetes.io/name=backend
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: backend_pods

    - name: Show backend pods
      debug:
        var: backend_pods.stdout_lines

    - name: Check backend logs (last 30 lines)
      shell: kubectl logs -n meo-stationery -l app.kubernetes.io/name=backend --tail=30
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: backend_logs
      ignore_errors: yes

    - name: Show backend logs
      debug:
        var: backend_logs.stdout_lines

    - name: Check ingress configuration
      shell: kubectl describe ingress backend -n meo-stationery
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: ingress_desc
      ignore_errors: yes

    - name: Show ingress description
      debug:
        var: ingress_desc.stdout_lines

    - name: Check ingress controller service
      shell: kubectl get svc -n ingress-nginx ingress-nginx-controller -o yaml
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: ingress_svc

    - name: Show ingress service details
      debug:
        var: ingress_svc.stdout_lines

    - name: Test backend service directly
      shell: kubectl run test-backend --image=curlimages/curl:latest --rm -i --restart=Never -n meo-stationery -- curl -v http://backend.meo-stationery.svc.cluster.local
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: backend_direct_test
      ignore_errors: yes

    - name: Show backend direct test
      debug:
        var: backend_direct_test.stdout_lines

    - name: Test ingress routing from inside cluster
      shell: kubectl run test-ingress --image=curlimages/curl:latest --rm -i --restart=Never -n meo-stationery -- curl -H "Host: meo-stationery.local" -v http://ingress-nginx-controller.ingress-nginx.svc.cluster.local
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: ingress_internal_test
      ignore_errors: yes

    - name: Show ingress internal test
      debug:
        var: ingress_internal_test.stdout_lines

    - name: Get NodePort
      shell: kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.spec.ports[?(@.name=="http")].nodePort}'
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: nodeport

    - name: Test NodePort from server
      shell: 'curl -H "Host: meo-stationery.local" http://localhost:{{ nodeport.stdout }} -v -m 5'
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: nodeport_test
      ignore_errors: yes

    - name: Show NodePort test
      debug:
        var: nodeport_test.stdout_lines

    - name: Check security group rules
      shell: aws ec2 describe-security-groups --group-names k8s-sg --query 'SecurityGroups[0].IpPermissions' --output json
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: sg_rules
      ignore_errors: yes

    - name: Show security group rules
      debug:
        var: sg_rules.stdout_lines

