- name: Check Postgres and Storage Status
  hosts: masters
  become: yes
  vars:
    master_kubeconfig: /home/ubuntu/.kube/config

  tasks:
    - name: Check postgres pod details
      shell: kubectl describe pod postgres-0 -n meo-stationery
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: postgres_describe
      ignore_errors: yes

    - name: Show postgres pod details
      debug:
        var: postgres_describe.stdout_lines

    - name: Check PVC status
      shell: kubectl get pvc -n meo-stationery
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: pvc_status

    - name: Show PVC status
      debug:
        var: pvc_status.stdout_lines

    - name: Check EBS CSI Driver pods
      shell: kubectl get pods -n kube-system | grep ebs
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: ebs_pods
      ignore_errors: yes

    - name: Show EBS CSI Driver pods
      debug:
        var: ebs_pods.stdout_lines

    - name: Check storage classes
      shell: kubectl get storageclass
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: storage_classes

    - name: Show storage classes
      debug:
        var: storage_classes.stdout_lines

