- name: Quick Fix Postgres with hostPath Storage
  hosts: masters
  become: yes
  vars:
    master_kubeconfig: /home/ubuntu/.kube/config

  tasks:
    - name: Create hostPath storage class
      shell: |
        kubectl apply -f - <<'EOF'
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: hostpath
          annotations:
            storageclass.kubernetes.io/is-default-class: "true"
        provisioner: kubernetes.io/no-provisioner
        volumeBindingMode: WaitForFirstConsumer
        EOF
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"

    - name: Delete existing postgres resources
      shell: |
        kubectl delete statefulset postgres -n meo-stationery --ignore-not-found=true
        kubectl delete pvc postgres-storage-postgres-0 -n meo-stationery --ignore-not-found=true
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      ignore_errors: yes

    - name: Wait for cleanup
      pause:
        seconds: 5

    - name: Create PersistentVolume for postgres
      shell: |
        kubectl apply -f - <<'EOF'
        apiVersion: v1
        kind: PersistentVolume
        metadata:
          name: postgres-pv
        spec:
          capacity:
            storage: 1Gi
          accessModes:
            - ReadWriteOnce
          persistentVolumeReclaimPolicy: Retain
          storageClassName: hostpath
          hostPath:
            path: /mnt/postgres-data
            type: DirectoryOrCreate
        EOF
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"

    - name: Create PersistentVolumeClaim
      shell: |
        kubectl apply -f - <<'EOF'
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: postgres-storage-postgres-0
          namespace: meo-stationery
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: hostpath
          volumeName: postgres-pv
        EOF
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"

    - name: Update database values to use hostpath storage class
      copy:
        content: |
          nameOverride: "postgres"
          fullnameOverride: "postgres"

          image:
            repository: postgres
            pullPolicy: Always
            tag: "13"

          service:
            type: ClusterIP
            port: 5432

          serviceAccount:
            create: false

          auth:
            username: "meo_admin"
            password: "MeoStationery2025!"
            database: "meo_stationery"

          persistence:
            size: 1Gi
            storageClassName: "hostpath"
            provisionStorageClass: false

          livenessProbe:
            enabled: true
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
        dest: /home/ubuntu/k8s_helm/database/values.yaml

    - name: Redeploy postgres
      command: >
        helm upgrade postgres database
        --namespace meo-stationery
        --values database/values.yaml
        --install
      args:
        chdir: /home/ubuntu/k8s_helm
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"

    - name: Wait for postgres to start
      pause:
        seconds: 15

    - name: Check postgres status
      shell: kubectl get pods -n meo-stationery -l app.kubernetes.io/name=postgres
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: postgres_status

    - name: Show postgres status
      debug:
        var: postgres_status.stdout_lines

