- name: Install EBS CSI Driver and Fix Storage
  hosts: masters
  become: yes
  vars:
    master_kubeconfig: /home/ubuntu/.kube/config

  tasks:
    - name: Remove broken Helm apt source list (cleanup)
      file:
        path: /etc/apt/sources.list.d/helm-stable-debian.list
        state: absent

    - name: Install Helm using official script
      shell: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        rm get_helm.sh
      args:
        creates: /usr/local/bin/helm

    - name: Add AWS EBS CSI Driver Helm repository
      shell: helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      ignore_errors: yes

    - name: Update Helm repositories
      shell: helm repo update
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"

    - name: Install AWS EBS CSI Driver
      shell: |
        helm upgrade --install aws-ebs-csi-driver aws-ebs-csi-driver/aws-ebs-csi-driver \
          --namespace kube-system \
          --set controller.serviceAccount.create=true \
          --set controller.serviceAccount.name=ebs-csi-controller-sa \
          --set node.serviceAccount.create=true \
          --set node.serviceAccount.name=ebs-csi-node-sa
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      ignore_errors: yes

    - name: Wait for EBS CSI Driver to be ready
      shell: kubectl wait --for=condition=ready pod -l app=ebs-csi-controller -n kube-system --timeout=300s
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      ignore_errors: yes

    - name: Create default EBS storage class
      shell: |
        kubectl apply -f - <<EOF
        apiVersion: storage.k8s.io/v1
        kind: StorageClass
        metadata:
          name: gp3
          annotations:
            storageclass.kubernetes.io/is-default-class: "true"
        provisioner: ebs.csi.aws.com
        volumeBindingMode: WaitForFirstConsumer
        parameters:
          type: gp3
          fsType: ext4
        EOF
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      ignore_errors: yes

    - name: Delete existing postgres StatefulSet and PVC
      shell: |
        kubectl delete statefulset postgres -n meo-stationery --ignore-not-found=true
        kubectl delete pvc postgres-storage-postgres-0 -n meo-stationery --ignore-not-found=true
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      ignore_errors: yes

    - name: Wait for cleanup
      pause:
        seconds: 5

    - name: Copy Helm charts to master
      copy:
        src: "../k8s_helm/"
        dest: "/home/ubuntu/k8s_helm/"
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      become: yes

    - name: Redeploy postgres with fixed configuration
      shell: |
        cd /home/ubuntu/k8s_helm
        helm upgrade postgres database \
          --namespace meo-stationery \
          --create-namespace \
          --values database/values.yaml \
          --install
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      ignore_errors: yes

    - name: Check postgres pod status
      shell: kubectl get pods -n meo-stationery -l app.kubernetes.io/name=postgres
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: postgres_status

    - name: Display postgres status
      debug:
        var: postgres_status.stdout_lines











