- name: Install Prometheus and Grafana Stack
  hosts: masters
  become: yes
  vars:
    master_kubeconfig: /home/ubuntu/.kube/config

  tasks:
    - name: Add Prometheus Community Helm repository
      shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"

    - name: Update Helm repositories
      shell: helm repo update
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"

    - name: Create monitoring namespace
      shell: kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"

    - name: Clean up evicted and failed pods before installation
      shell: |
        # Delete evicted pods
        kubectl get pods --all-namespaces -o json | grep -A 5 '"reason":"Evicted"' | grep '"name"' | sed 's/.*"name":"\([^"]*\)".*/\1/' | while read name; do
          kubectl delete pod "$name" --all-namespaces --ignore-not-found=true 2>/dev/null || true
        done
        # Clean up old Grafana pods
        kubectl delete pods -n monitoring -l app.kubernetes.io/name=grafana --field-selector=status.phase!=Running --ignore-not-found=true || true
        echo "Cleaned up evicted/failed pods"
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      ignore_errors: yes

    - name: Clean up unused Docker images to free disk space
      shell: |
        # Clean up unused Docker images (keep last 24 hours)
        docker system prune -af --filter "until=24h" || true
        echo "Cleaned up unused Docker images"
      ignore_errors: yes

    - name: Install kube-prometheus-stack (includes Prometheus and Grafana)
      shell: |
        helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
          --namespace monitoring \
          --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false \
          --set prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues=false \
          --set prometheus.prometheusSpec.ruleSelectorNilUsesHelmValues=false \
          --set grafana.adminPassword=admin \
          --set grafana.replicas=1 \
          --set grafana.service.type=ClusterIP \
          --set grafana.service.name=grafana \
          --set grafana.service.port=80 \
          --set grafana.resources.requests.memory=128Mi \
          --set grafana.resources.requests.cpu=100m \
          --set grafana.resources.limits.memory=512Mi \
          --set grafana.resources.limits.cpu=500m \
          --set prometheus.service.type=ClusterIP \
          --set prometheus.service.name=prometheus-server \
          --set prometheus.service.port=9090 \
          --set prometheus.prometheusSpec.retention=2d \
          --set prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage=2Gi \
          --set prometheus.prometheusSpec.resources.requests.memory=512Mi \
          --set prometheus.prometheusSpec.resources.requests.cpu=200m \
          --set prometheus.prometheusSpec.resources.limits.memory=2Gi \
          --set prometheus.prometheusSpec.resources.limits.cpu=1000m \
          --set prometheus.serviceMonitor.selector.matchLabels.app=postgres-exporter \
          --wait --timeout=10m
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"

    - name: Wait for Prometheus to be ready
      shell: |
        # Wait for Prometheus pod to be scheduled and running, with more lenient checks
        for i in {1..60}; do
          POD_PHASE=$(kubectl get pods -n monitoring -l app.kubernetes.io/name=prometheus -o jsonpath='{.items[0].status.phase}' 2>/dev/null || echo 'Unknown')
          if [ "$POD_PHASE" = "Running" ]; then
            READY=$(kubectl get pods -n monitoring -l app.kubernetes.io/name=prometheus -o jsonpath='{.items[0].status.containerStatuses[0].ready}' 2>/dev/null || echo 'false')
            if [ "$READY" = "true" ]; then
              echo "Prometheus pod is ready"
              exit 0
            fi
          fi
          if [ $((i % 10)) -eq 0 ]; then
            echo "Waiting for Prometheus... ($i/60) - Phase: $POD_PHASE"
            kubectl get pods -n monitoring -l app.kubernetes.io/name=prometheus | head -2 || true
          fi
          sleep 5
        done
        echo "Prometheus may not be fully ready, but continuing..."
        exit 0
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      ignore_errors: yes

    - name: Wait for Grafana to be ready
      shell: |
        # Wait for at least one Grafana pod to be ready, with more lenient checks
        for i in {1..60}; do
          READY_PODS=$(kubectl get pods -n monitoring -l app.kubernetes.io/name=grafana --field-selector=status.phase=Running -o jsonpath='{.items[*].status.containerStatuses[?(@.ready==true)]}' 2>/dev/null | wc -l)
          if [ "$READY_PODS" -gt 0 ]; then
            echo "Grafana pod is ready"
            exit 0
          fi
          echo "Waiting for Grafana... ($i/60)"
          sleep 5
        done
        echo "Grafana may not be fully ready, but continuing..."
        exit 0
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      ignore_errors: yes

    - name: Get Grafana service name
      shell: kubectl get svc -n monitoring -l app.kubernetes.io/name=grafana -o jsonpath='{.items[0].metadata.name}'
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: grafana_service_name
      ignore_errors: yes

    - name: Get Prometheus service name
      shell: kubectl get svc -n monitoring -l app=kube-prometheus-stack-prometheus -o jsonpath='{.items[0].metadata.name}' || kubectl get svc -n monitoring -l app.kubernetes.io/name=prometheus -o jsonpath='{.items[0].metadata.name}' || echo "prometheus-kube-prometheus-prometheus"
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: prometheus_service_name
      ignore_errors: yes
      changed_when: false

    - name: Display monitoring status
      debug:
        msg: |
          Prometheus and Grafana installed!
          Grafana Service: {{ grafana_service_name.stdout | default('prometheus-grafana') }}
          Prometheus Service: {{ prometheus_service_name.stdout | default('prometheus-kube-prometheus-prometheus') }}
          Access Grafana at: http://grafana.local (after ingress is configured)
          Access Prometheus at: http://prometheus.local (after ingress is configured)

