- name: Install ArgoCD
  hosts: masters
  become: yes
  vars:
    master_kubeconfig: /home/ubuntu/.kube/config

  tasks:
    - name: Add ArgoCD Helm repository
      shell: helm repo add argo https://argoproj.github.io/argo-helm
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"

    - name: Update Helm repositories
      shell: helm repo update
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"

    - name: Create argocd namespace
      shell: kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"

    - name: Install ArgoCD
      shell: |
        helm upgrade --install argocd argo/argo-cd \
          --namespace argocd \
          --set server.ingress.enabled=true \
          --set server.ingress.ingressClassName=nginx \
          --set server.ingress.hosts={argocd.local} \
          --set server.ingress.annotations."nginx\.ingress\.kubernetes\.io/force-ssl-redirect"="false" \
          --set server.ingress.annotations."nginx\.ingress\.kubernetes\.io/ssl-redirect"="false" \
          --set server.ingress.annotations."nginx\.ingress\.kubernetes\.io/backend-protocol"="HTTP" \
          --set server.extraArgs={--insecure} \
          --set configs.params.server.insecure=true \
          --wait --timeout=10m
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"

    - name: Wait for ArgoCD server to be ready
      shell: kubectl wait --namespace argocd --for=condition=ready pod --selector=app.kubernetes.io/name=argocd-server --timeout=300s
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      ignore_errors: yes

    - name: Get ArgoCD admin password
      shell: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      register: argocd_password
      ignore_errors: yes

    - name: Display ArgoCD status
      debug:
        msg: |
          ArgoCD installed!
          Access ArgoCD at: http://argocd.local
          Username: admin
          Password: {{ argocd_password.stdout | default('Check secret: kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d') }}

    - name: Patch ArgoCD Ingress Host (Fix)
      shell: |
        kubectl patch ingress argocd-server -n argocd --type=json -p='[{"op": "replace", "path": "/spec/rules/0/host", "value": "argocd.local"}]'
      environment:
        KUBECONFIG: "{{ master_kubeconfig }}"
      ignore_errors: yes


